### ISSUE TITLE
problem with script

### ISSUE THREAD

**Issue by mtk64** [Thyraz/snips-volume#1]
Hi,
just tried out to use the script, but there is no reaction.
So I started it via CLI and used MQTT Explorer to set hermes/sound/setvolume
Just published 50 in json format to MQTT on snips and got this error: 

root@snips1:~# python3 /opt/snips-volume/snips-volume.py
MQTT connected
Traceback (most recent call last):
  File "/opt/snips-volume/snips-volume.py", line 107, in <module>
    client.loop_forever()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "/opt/snips-volume/snips-volume.py", line 54, in on_set
    target_id = data['siteId']
TypeError: 'int' object is not subscriptable

When setting volume in FHEM via set command there is no reaction.
Any idea what is going wrong on my installation?
Or any mistakes from my side during testing?

kind regards
michael

**Comment by mtk64** [comment]
meanwhile I got it to react on MQTT setvolume via MQTT Explorer. JSON Format was not correct.
This one is working:
{
  "siteId": "default",
  "volume": 90
}

Now i will try to find out why FHEM is not setting volume ...
